server:
  port: 8080

spring:
  application:
    name: Library Management System

  datasource:
    url: jdbc:postgresql://localhost:5432/LibraryManagementSystem   # change "mydb" to your DB name
    username: postgres                           # your DB username
    password: coder                           # your DB password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update                           # update schema automatically (dev only)
    show-sql: true                               # logs SQL queries
    properties:
      hibernate:
        format_sql: true

  sql:
    init:
      mode: always                               # can be never, embedded, always
      platform: postgres

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: "546083712154-m8mb5iu88q7fb1m6gl34m3keun78ipp7.apps.googleusercontent.com"
            client-secret: "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"
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope:
              - openid
              - profile
              - email
          github:
            client-id: "Ov23liBqfP9hGZ7q32hf"
            client-secret: "044a9a390a09b1d83f4e46c6535a6910ccfcbcdf"
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope:
              - user:email
        provider:
          google:
            issuer-uri: https://accounts.google.com
          github:
            authorization-uri: https://github.com/login/oauth/authorize
            token-uri: https://github.com/login/oauth/access_token
            user-info-uri: https://api.github.com/user

logging:
  level:
    org.springframework.security: INFO
    org.hibernate.SQL: DEBUG
