server:
  port: 8080
#  servlet:
#    context-path: /api

spring:
  application:
    name: Library Management System

  datasource:
    url: jdbc:postgresql://localhost:5432/LibraryManagementSystem   # change "mydb" to your DB name
    username: postgres                           # your DB username
    password: sipl                           # your DB password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update                           # update schema automatically (dev only)
    show-sql: false                               # logs SQL queries
    properties:
      hibernate:
        format_sql: true

  sql:
    init:
      mode: always                               # can be never, embedded, always
      platform: postgres

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: "546083712154-m8mb5iu88q7fb1m6gl34m3keun78ipp7.apps.googleusercontent.com"
            client-secret: "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"
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope:
              - openid
              - profile
              - email
          github:
            client-id: "Ov23liBqfP9hGZ7q32hf"
            client-secret: "044a9a390a09b1d83f4e46c6535a6910ccfcbcdf"
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope:
              - read:user
              - user:email
        provider:
          google:
            user-name-attribute: sub
          github:
            user-name-attribute: id

logging:
  level:
    org.springframework.security: INFO
    org.springframework.web.client.RestTemplate: DEBUG
    #org.hibernate.SQL: DEBUG

app:
  scheduler:
    overdue-cron: "0 10 23 * * ?" # runs every day at midnight
  jwt:
    secret: "DfBmNudo3TjrbcOMgFe+rM3t9vHs2Ez8vlkqouDaYyOK2qOQfUjTVts9SLoYVgyIcwQNA7vpZfP0XfxeR8Sdjw=="
